name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@v3.1.0
        with:
          purescript: latest
          spago: latest

      - name: Run unit tests
        run: spago test
  
